#!/usr/bin/env bash
#
# Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
#
# 一键安装脚本（幂等，可重复执行）：
#   1. 前置检查：php>=8.3 / composer / mysql 客户端 / openssl
#   2. composer install（service/、admin/，--no-dev；vendor 已存在则跳过）
#   3. 创建 social + open_admin 数据库
#   4. 导入 database/install.sql（social 段可重复执行；open_admin 段已安装则跳过，不破坏数据）
#   5. 生成 service/.env 与 admin/.env（已存在不覆盖，密钥 openssl rand 生成）
#   6. 可选启动 media/sfu 容器（--skip-media 跳过）
#
# 用法: ./install.sh [--skip-media]
# 环境变量: DB_HOST DB_PORT DB_USERNAME DB_ROOT_PASSWORD（缺省时交互询问密码）
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SKIP_MEDIA=0
for arg in "$@"; do
  case "$arg" in
    --skip-media) SKIP_MEDIA=1 ;;
    *) echo "未知参数: $arg（支持 --skip-media）" >&2; exit 1 ;;
  esac
done

# ─────────────────────────── 前置检查 ───────────────────────────

require() { command -v "$1" >/dev/null 2>&1 || { echo "缺少依赖: $1，请先安装" >&2; exit 1; }; }

require php
PHP_VER="$(php -r 'echo PHP_MAJOR_VERSION . "." . PHP_MINOR_VERSION;' 2>/dev/null || echo 0.0)"
if [[ "$PHP_VER" < "8.3" ]]; then
  echo "PHP >= 8.3 必需（当前 $PHP_VER）" >&2
  exit 1
fi
require composer
require mysql
require redis-cli
require openssl
echo "前置检查通过（PHP $PHP_VER / composer / mysql / redis-cli / openssl）"

# ─────────────────────────── 数据库连接 ───────────────────────────

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-3306}"
DB_USERNAME="${DB_USERNAME:-root}"
if [[ -z "${DB_ROOT_PASSWORD:-}" ]]; then
  read -rsp "MySQL $DB_USERNAME@$DB_HOST 密码: " DB_ROOT_PASSWORD
  echo
fi
export MYSQL_PWD="$DB_ROOT_PASSWORD"   # 避免密码出现在 ps 输出
MYSQL=(mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USERNAME")
if ! "${MYSQL[@]}" -e "SELECT 1" >/dev/null 2>&1; then
  echo "无法连接 MySQL（$DB_USERNAME@$DB_HOST:$DB_PORT），请检查密码" >&2
  exit 1
fi
echo "MySQL 连接成功"

# ─────────────────────────── composer install ───────────────────────────

composer_install() {
  local dir="$1"
  if [[ -d "$dir/vendor" ]]; then
    echo "$dir/vendor 已存在，跳过 composer install"
  else
    echo "composer install（$dir）..."
    (cd "$dir" && composer install --no-interaction --no-dev --no-progress)
  fi
}
composer_install "$ROOT/service"
composer_install "$ROOT/admin"

# ─────────────────────────── 建库 + 导入 ───────────────────────────

echo "创建数据库 social / open_admin ..."
"${MYSQL[@]}" -e "CREATE DATABASE IF NOT EXISTS \`social\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`open_admin\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

# install.sql 混含 social_（CREATE IF NOT EXISTS，幂等）与 erik_（DROP 重建）两类表：
#   social 段 = 1-184 行 + 445 行至文件尾（虚拟经济/支付/提现均为 social_ 表）
#   open_admin 段 = 185-444 行（含权限/角色/用户种子）
INSTALL_SQL="$ROOT/database/install.sql"

echo "导入 social 段（可重复执行，CREATE IF NOT EXISTS）..."
sed -n '1,184p;445,$p' "$INSTALL_SQL" | "${MYSQL[@]}" social

# CREATE TABLE IF NOT EXISTS 对已存在表是 no-op，需显式去掉这三张表的 AUTO_INCREMENT：
# 主键改由应用层 snowflake 生成（Rust idgen_rs），残留自增与显式传入的 id 语义不明。
echo "移除 live/voice room 三表的 AUTO_INCREMENT ..."
"${MYSQL[@]}" social -e "
ALTER TABLE social_live_rooms MODIFY id BIGINT UNSIGNED NOT NULL COMMENT '主键ID，由snowflake生成';
ALTER TABLE social_voice_rooms MODIFY id BIGINT UNSIGNED NOT NULL COMMENT '主键ID，由snowflake生成';
ALTER TABLE social_voice_room_members MODIFY id BIGINT UNSIGNED NOT NULL COMMENT '主键ID，由snowflake生成';"

if "${MYSQL[@]}" open_admin -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='open_admin' AND table_name='erik_admin_user'" | grep -q '^0$'; then
  echo "导入 open_admin 段（首次安装）..."
  sed -n '185,444p' "$INSTALL_SQL" | "${MYSQL[@]}" open_admin
else
  echo "open_admin 已安装（跳过重建，保留现有数据）"
fi

# ─────────────────────────── 生成 .env ───────────────────────────

gen_key() { openssl rand -hex "$1"; }

# 用 printf %s 写密码/密钥，避免特殊字符（$ # 空格等）被 shell 或 .env 解析破坏
write_env() {
  local file="$1"
  [[ -f "$file" ]] && { echo "已存在: $file（不覆盖）"; return 1; }
  {
    echo "# Generated by install.sh $(date '+%F %T')"
    echo "DB_CONNECTION=mysql"
    printf 'DB_HOST=%s\nDB_PORT=%s\nDB_USERNAME=%s\nDB_PASSWORD=%s\n' \
      "$DB_HOST" "$DB_PORT" "$DB_USERNAME" "$DB_ROOT_PASSWORD"
    echo "REDIS_HOST=127.0.0.1"
    echo "REDIS_PORT=6379"
    echo "REDIS_PASSWORD="
    echo "REDIS_DATABASE=0"
    printf 'JWT_SECRET=%s\n' "$(gen_key 32)"
    printf 'ENCRYPTABLE_KEY=%s\n' "$(gen_key 16)"
    echo "ENCRYPTABLE_CIPHER=aes-128-ecb"
  } > "$file"
}

# service/.env：social 库（DB_PREFIX=social_）+ 跨库读 open_admin
if [[ ! -f "$ROOT/service/.env" ]]; then
  write_env "$ROOT/service/.env"
  {
    echo "DB_DATABASE=social"
    echo "DB_PREFIX=social_"
    echo "DB_OPEN_ADMIN_DATABASE=open_admin"
    printf 'HASHIDS_SALT=%s\n' "$(gen_key 16)"
  } >> "$ROOT/service/.env"
  echo "已生成: $ROOT/service/.env"
fi

# admin/.env：open_admin 库（默认库）+ 跨库读 social
if [[ ! -f "$ROOT/admin/.env" ]]; then
  write_env "$ROOT/admin/.env"
  {
    echo "DB_DATABASE=open_admin"
    echo "DB_SOCIAL_DATABASE=social"
    echo "REDIS_PREFIX=open-admin:"
    printf 'JWT_SECRET_KEY=%s\n' "$(gen_key 32)"
  } >> "$ROOT/admin/.env"
  echo "已生成: $ROOT/admin/.env"
fi

# ─────────────────────────── media/sfu 容器（可选） ───────────────────────────

if [[ "$SKIP_MEDIA" -eq 1 ]]; then
  echo "跳过 media/sfu 容器（--skip-media）"
elif command -v docker >/dev/null 2>&1; then
  echo "启动 media/sfu 容器（语音/通话）..."
  (cd "$ROOT/media/sfu" && docker compose up -d)
else
  echo "未安装 docker，跳过 media/sfu（需要时可手动启动）"
fi

# ─────────────────────────── 完成 ───────────────────────────

echo
echo "安装完成。启动服务："
echo "  service:  cd $ROOT/service && php start.php start -d   # http://0.0.0.0:8788"
echo "  admin:    cd $ROOT/admin && php start.php start -d     # http://0.0.0.0:8791"
echo "后台默认账号: erik（密码见 database/install.sql 种子，首次登录后请修改）"
