# Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
[package]
name = "bee_search"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror.workspace = true
reqwest = { workspace = true, optional = true }

[features]
default = []
elasticsearch = ["dep:reqwest"]
opensearch = ["dep:reqwest"]
clickhouse = ["dep:reqwest"]

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
axum = { workspace = true }
serde = { workspace = true }
