[package]
name = "social_grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
tonic = "0.12"
tonic-health = "0.12"
prost = "0.13"
serde_json = { workspace = true }
bee_search = { path = "../bee_search", features = ["elasticsearch"] }

[build-dependencies]
tonic-build = "0.12"
